ARG platform

# for x86/64 build (es: Docker for PC)
FROM python:latest as branch_pc

# for aarch64 build (es: Docker for Raspberry)
FROM arm64v8/ubuntu as branch_arm

# a sort of switch case
FROM branch_${platform} AS final 
RUN echo "You are using ${platform} image!"

VOLUME "/heikinashichaser"
COPY externalPackage/*.whl /externalPackage/

RUN apt-get update
RUN apt-get install -y build-essential checkinstall
RUN apt install -y python3
RUN apt-get -y install python3-pip
RUN python3 -m pip install --upgrade pip

RUN pip install externalPackage/*.whl

WORKDIR /heikinashichaser

CMD ["python3", "src/heikinashichaser/main.py"]