FROM python:latest

COPY . /heikinAshiObserver
WORKDIR /heikinAshiObserver

RUN apt-get update
RUN apt-get install -y build-essential checkinstall
RUN python -m pip install --upgrade pip
RUN python -m pip install externalPackage/tradingBot-0.1.0-py3-none-any.whl

CMD ["python", "src/heikinashichaser/main.py"]
